### ISSUE TITLE
Error in the documentation. Section "pattern library"

### ISSUE THREAD

**Issue by mg901** [oddbird/accoutrement-layout#1] opened 2017-04-17 14:25 UTC
Hi, Miriam! I tried to set breakpoints and just copied from the documentation
[that's it](http://joxi.ru/n2YkX6kToRG4dr)

Then there was an error

 banner-text is not a valid length for CSS.
        on line 45 of node_modules/accoutrement-scale/sass/_size.scss
>>     @error '#{$size} is not a valid length for CSS.';

I tried to combine the maps in the same way as described in the documentation for [accoutrement-color]( http://joxi.ru/l2ZNxWNswaDZK2) 

 I just called the map-merge function

$sizes: map-merge ($ sizes, $ breakpoints);

**Comment by mirisuzanne** [comment] 2017-04-17 17:55
You were trying to merge size/breakpoint maps using the color-merge functions? We could add similar mixins to `accoutrement-scale` or `accoutrement-layout` but I don't see any documents claiming that we have.

If you were trying to merge `$sizes` and `$breakpoints` - there's no need to do that. We don't show that in the documentation because it's not needed. We automatically look at `$sizes` if we can't find a named breakpoint in the `$breakpoints` map. These don't need to be merged manually.

**Comment by mg901** [comment] 2017-04-17 18:01
$breakpoints: (
  'xsmall': 0px,
  'small': 640px,
  'medium': 1024px,
  'large': 1200px,
);

.container {
  @include below('large') {
    background-color: black;
  }

  @include above('medium') {
    background-color: red;
  }
}


No, I do want to say that if you declare map $breakpoints and try to take a value out of it, it's welcome to the error.
And that the $sizes: map-merge ($sizes, $breakpoints) arranges this error.



Error: large is not a valid length for CSS.
        on line 45 of node_modules/accoutrement-scale/sass/_size.scss
>>     @error '#{$size} is not a valid length for CSS.';
   ----^

**Comment by mirisuzanne** [comment] 2017-04-17 18:18
Aha! I see the problem, and I tracked down the cause to the [Get Breakpoint](https://github.com/oddbird/accoutrement-layout/blob/master/sass/_queries.scss#L14) function. I'll work on a fix. Thanks for reporting this!

**Comment by mg901** [comment] 2017-04-17 18:22
Thank you, Miriam!) If you are limited in time, I would be happy to help you with bug fixes. Since what you have done is, in my opinion, the best decision of all that I have seen and I look forward to using it in my projects.))

**Comment by mirisuzanne** [comment] 2017-04-17 18:49
Should be fixed in b175085dc06e5f39a7134d5ec7721fa687ca5ba5 (and the 2.1.1 release)

**Comment by mirisuzanne** [comment] 2017-04-17 18:50
Thanks for the offer! I'd take you up on it, but I didn't see your offer until it was already resolved. :)

**Closed as completed by mirisuzanne** 2017-04-17 18:49 UTC
Labels: bug
