### ISSUE TITLE
Incorrect data when displaying z-index values

### ISSUE THREAD

**Issue by mg901** [oddbird/accoutrement-layout#2] opened 2017-04-17 14:36 UTC
I tried the z-index map in action.
[The z-index of these elements is not true](http://joxi.ru/v29WG5WS3Odkxr)

a) @debug z-index('banner') == 3
b) @debug z-index('active-nav') == 2
c) @debug z-index('dropdown') == 3;

**Comment by mirisuzanne** [comment] 2017-04-17 17:45
This is currently the expected behavior, though not well documented. It's meant to account for different contexts - assuming `active-nav` and `dropdown` are nested inside the `banner`. Since z-index is scoped, We can reset the counter inside each context.

Maybe you were expecting all three to have the same z-index? That's a reasonable assumption, given our lack of documentation. We should make it more clear.

**Comment by mg901** [comment] 2017-04-17 17:52
Yes, I thought they were all on the same plane and had the same z-index. Many thanks for the prompt reply.))

**Comment by mirisuzanne** [comment] 2017-08-28 21:23
Closed by 7c74f4c

**Closed as completed by mirisuzanne** 2017-08-28 21:23 UTC
Labels: needs documentation
